### ISSUE TITLE
Usage with `commonjs` & `node-resolve`?

### ISSUE THREAD

**Issue by leebenson** [dot-build/rollup-plugin-includepaths#12]
I have multiple imports like this:

```js
import react from 'react'; // <-- node_modules
import somethingLocal from 'some/placeLocal'; // <-- relative to ./src/
```

Using `rollup-plugin-includepaths` works well on its own, but I also want to include external dependencies in _node_modules_ in my bundle. Using alongside [commonjs](https://github.com/rollup/rollup-plugin-commonjs) and [node-resolve](https://github.com/rollup/rollup-plugin-node-resolve) causes errors like:

> Could not resolve 'shared/store'

i.e. it can't differentiate between global mods, and what I've specified as being local.

Usage instructions in the readme would be a big help, thanks.

**Comment by darlanalves** [comment]
Hello!
Can you share some details about your rollup config file? e.g. includepaths options and the order of plugin execution.

includepaths plugin will just try to resolve the included modules in a given list of source folders, by appending the module file after every source path and matching files on disk. If that module is not available, the next plugin will try to resolve it.

I guess your plugin order may be an issue here, as `shared/store` seems to mean `look for 'store.js' inside node_modules/shared folder` instead of resolving local project files under `src` directory.

**Comment by leebenson** [comment]
I've switched back to webpack 2 in the interim and have removed my rollup config. I'll close this issue for now, and will report back if there are further issues. Thanks.
