### ISSUE TITLE
0.1.4 caused `TypeError: rollupIncludePaths is not a function` on Ubuntu 16.04

### ISSUE THREAD

**Issue by martianyi** [dot-build/rollup-plugin-includepaths#6]
I'm using the es5 version, requiring it like this, `var rollupIncludePaths = require('rollup-plugin-includepaths');`. 

 when I downgrade to 0.1.2, it works fine.

**Comment by darlanalves** [comment]
Hello!

I'm terribly sorry for this. Since yesterday I added a simple build task for ES5 version with Babel 6.x. It turns out that `babel@6.x` is not exporting the `module.exports` bindings for CommonJS modules anymore. 

[v0.1.5](https://github.com/dot-build/rollup-plugin-includepaths/releases/tag/v0.1.5) fixed this issue.

This module fixed the issue in the build BTW:
https://www.npmjs.com/package/babel-plugin-add-module-exports

**Comment by martianyi** [comment]
Ok, thanks.
