### ISSUE TITLE
Not working with rollup-plugin-node-builtins

### ISSUE THREAD

**Issue by StreetStrider** [dot-build/rollup-plugin-includepaths#8]
Looks like this plugin don't work well in company with `rollup-plugin-node-builtins`.

My goal is to use IO-free modules like node std `path` in my bundle. This works ok if includepaths is disabled. However, when I enable it I got error `No name was provided for external module 'path' in options.globals – guessing 'path'`. I've tried to rearrange my plugins, move includepaths down or up. I've also tried to use `external: [ 'path' ]` option, but it didn't work for me. I got the same error no matter the config state.

Is it possible to make them work together or I just missing something and `includepaths` isn't meant to work in such case? Will glad any help or tips.

**Comment by darlanalves** [comment]
Hello!

I can't reproduce your problem using only the includepaths plugin and the builtins plugin together. The issue seems to be somewhere else.

This is the config I used to run a test:
https://gist.github.com/darlanalves/8bce333fdec2891991af2ecf3b1790e1

Running rollup with these files and then running the final `app.js` with node will show a list of methods on path module.

**Comment by StreetStrider** [comment]
@darlanalves, hello and thanks for response.
I've prepared a [simple configuration](https://github.com/StreetStrider/includepath-issue) which mimics my problem one.

At this revision everything is ok. I can resolve `path` builtin (however not using it, so Rollup effectively reduces it to single function expression). Then I uncomment `include` (3) and get warning about `path`, and it stops resolving. Then I can uncomment (1) or (2) to show that `include` not working as well.

**Comment by darlanalves** [comment]
Hello!

I've ran your setup. Indeed there are some issues there but they're due to config only.
Changing the builtins and includepath configs to this will build sucessfully:

```
plugins: [
	include({ external: [], paths: [ 'buns' ] }),
	builtins(),
	// ...
]
```

Some notes about it:
- includePaths plugin, by default, marks all the node builtins as external modules. This is not in the docs, my fault. I'm adding there to clarify. Due to this, since you did not mention the `external` config, it was leaving the `path` module outside the bundle.
- You don't need to add `__dirname` in the source paths. All the paths are resolved to current folder.
- A good practice, and a thing that will break rollup: Avoid running any module code before finishing all the imports. In your example, the `foo()` call before other imports.

And a side note about path: the builtins plugin had an issue, so you'll need to check for a new release that includes [this PR](https://github.com/calvinmetcalf/rollup-plugin-node-builtins/pull/9).

Here's [an updated](https://github.com/darlanalves/includepath-issue) setup working. Running the bundled file will present the list of available methods on `path` module.

Let me know if you're still facing issues :)

**Comment by StreetStrider** [comment]
@darlanalves, well I'm glad that issue is commonly on side of my config and not Rollup ecosystem.
Before this issue I was experimenting with `external` option both of [Rollup](https://github.com/rollup/rollup/wiki/JavaScript-API#external) and `includepaths`, but I exclude `path` by myself. Semees that I should *exclude* `path`, not include it in this option. Thanks for clarification here :+1: 

Passing empty array to `includepaths` external seemes working on my current workflow. :tada: 

* I've included dirname because I use not simple paths, but paths provided by [rootpath](https://github.com/StreetStrider/rootpath) — a tool which I use to expressively work with path hierarchies. So I have `__dirname` under hood and I wanted to be sure that my test configuration copies my battle one.

> Avoid running any module code before finishing all the imports.

* I totally agree with you, I just wanted to have ref to `foo`, so Rollup didn't shake it away.

What do you think about order of plugins? Does they order matter? Should `includepaths` go first? I'm not familiar with Plugins API well.

**Comment by StreetStrider** [comment]
[attached repo](https://github.com/dot-build/rollup-plugin-includepaths/files/349652/includepath-issue.tar.gz) with your solution included, for history.

**Comment by darlanalves** [comment]
I was confused as well at first, then I read a little bit the internals of rollup. The resolution order may be important, depending on how a given plugin works. For example, if you have a chain and you import `path` in your project, a plugin could either ignore the import because is a builtin, passing the responsibility to the next one in the chain, or "swallow" the import, breaking the expected result.

Rollup applies a resolution algorithm using chain of responsibility pattern, I think. But usually you should not have issues with the ordering.

**Comment by StreetStrider** [comment]
@darlanalves Thanks for help again.
